#!/usr/bin/env python3
"""
Interactive setup script for Notion integration.
Helps configure the .env file with Notion credentials.
"""

import os
import sys

def print_header():
    """Print welcome header."""
    print("=" * 70)
    print("Tiangong Research Database - Notion Integration Setup")
    print("=" * 70)
    print()

def print_section(title):
    """Print section header."""
    print()
    print(f">>> {title}")
    print("-" * 70)

def get_notion_token():
    """Get Notion integration token from user."""
    print_section("Step 1: Notion Integration Token")
    print("You need a Notion integration token to sync data.")
    print()
    print("To get your token:")
    print("1. Go to https://www.notion.so/my-integrations")
    print("2. Click '+ New integration'")
    print("3. Give it a name (e.g., 'Tiangong Database Sync')")
    print("4. Select your workspace")
    print("5. Click 'Submit'")
    print("6. Copy the 'Internal Integration Token' (starts with 'secret_' or 'ntn_')")
    print()
    
    while True:
        token = input("Enter your Notion integration token: ").strip()
        if token.startswith('secret_') or token.startswith('ntn_'):
            return token
        print("⚠️  Token should start with 'secret_' or 'ntn_'. Please try again.")
        print()

def get_database_id():
    """Get Notion database ID from user."""
    print_section("Step 2: Notion Database ID")
    print("You need the ID of your Notion database.")
    print()
    print("To get your database ID:")
    print("1. Open your Notion database in a browser")
    print("2. The URL looks like: https://www.notion.so/workspace/DATABASE_ID?v=...")
    print("3. Copy the DATABASE_ID part (32 character alphanumeric string)")
    print()
    print("Example URL: https://www.notion.so/workspace/abc123def456ghi789jkl012mno345pq?v=...")
    print("Database ID: abc123def456ghi789jkl012mno345pq")
    print()
    
    while True:
        db_id = input("Enter your Notion database ID: ").strip()
        # Remove hyphens if present
        db_id = db_id.replace('-', '')
        if len(db_id) == 32:
            return db_id
        print(f"⚠️  Database ID should be 32 characters long. You entered {len(db_id)} characters.")
        print()

def check_database_properties():
    """Remind user about required database properties."""
    print_section("Step 3: Database Properties")
    print("Make sure your Notion database has these properties:")
    print()
    properties = [
        ("Name", "Title"),
        ("Station", "Select with options: 'Tiangong' and 'ISS'"),
        ("Discipline", "Text"),
        ("Country/Institution", "Text"),
        ("Timeline Status", "Text"),
        ("Objectives", "Text"),
        ("Expected Outcomes", "Text"),
        ("Principal Investigator", "Text"),
        ("Mission Module", "Text"),
    ]
    
    for prop_name, prop_type in properties:
        print(f"  • {prop_name:<25} ({prop_type})")
    
    print()
    print("⚠️  IMPORTANT: The 'Station' property must be a 'Select' type with")
    print("   two options: 'Tiangong' and 'ISS'")
    print()
    
    response = input("Have you created these properties? (yes/no): ").strip().lower()
    if response not in ['yes', 'y']:
        print()
        print("Please create the required properties in your Notion database first.")
        print("Then run this script again.")
        sys.exit(0)

def check_integration_access():
    """Remind user to share database with integration."""
    print_section("Step 4: Share Database with Integration")
    print("Your integration needs access to the database.")
    print()
    print("To share your database:")
    print("1. Open your Notion database")
    print("2. Click the '...' menu in the top-right")
    print("3. Click 'Add connections'")
    print("4. Select your integration")
    print()
    
    response = input("Have you shared the database with your integration? (yes/no): ").strip().lower()
    if response not in ['yes', 'y']:
        print()
        print("Please share the database with your integration first.")
        print("Then run this script again.")
        sys.exit(0)

def create_env_file(token, db_id):
    """Create .env file with credentials."""
    print_section("Step 5: Creating .env file")
    
    env_content = f"""# Notion API Configuration
# Generated by setup_notion.py

# Notion Integration Token
NOTION_TOKEN={token}

# Notion Database ID
NOTION_DATABASE_ID={db_id}
"""
    
    env_path = ".env"
    
    # Check if .env already exists
    if os.path.exists(env_path):
        print(f"⚠️  File {env_path} already exists.")
        response = input("Do you want to overwrite it? (yes/no): ").strip().lower()
        if response not in ['yes', 'y']:
            print("Setup cancelled. No changes made.")
            sys.exit(0)
    
    # Write .env file
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print(f"✓ Created {env_path} with your credentials")
    print()

def run_test():
    """Offer to run test script."""
    print_section("Step 6: Test Configuration")
    print("Would you like to run the test script to verify everything works?")
    print()
    
    response = input("Run tests now? (yes/no): ").strip().lower()
    if response in ['yes', 'y']:
        print()
        print("Running tests...")
        print()
        import sys
        import subprocess
        try:
            subprocess.run([sys.executable, "test_sync.py"], check=True, shell=False)
        except subprocess.CalledProcessError as e:
            print(f"Tests failed with error: {e}")
        except Exception as e:
            print(f"Error running tests: {e}")
    else:
        print()
        print("You can run tests later with: python test_sync.py")

def print_next_steps():
    """Print next steps."""
    print()
    print("=" * 70)
    print("✓ Setup Complete!")
    print("=" * 70)
    print()
    print("Next steps:")
    print()
    print("1. Run tests (if you haven't already):")
    print("   python test_sync.py")
    print()
    print("2. Sync your data to Notion:")
    print("   python sync_to_notion.py")
    print()
    print("3. (Optional) Set up GitHub Actions for automatic sync:")
    print("   - Go to your repository Settings → Secrets and variables → Actions")
    print("   - Add NOTION_TOKEN and NOTION_DATABASE_ID as repository secrets")
    print()
    print("For more information, see README.md and USAGE.md")
    print()

def main():
    """Main setup function."""
    print_header()
    
    # Get credentials
    token = get_notion_token()
    db_id = get_database_id()
    
    # Check database setup
    check_database_properties()
    check_integration_access()
    
    # Create .env file
    create_env_file(token, db_id)
    
    # Run tests
    run_test()
    
    # Print next steps
    print_next_steps()

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print()
        print()
        print("Setup cancelled by user.")
        sys.exit(1)
